# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_memory.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chat_memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hat_memory.proto\x12\x0b\x63hat_memory\"T\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nsource_ids\x18\x03 \x03(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"[\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x19\n\x11relevant_memories\x18\x02 \x03(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"Q\n\x12\x41\x64\x64MemoriesRequest\x12*\n\x08messages\x18\x01 \x03(\x0b\x32\x18.chat_memory.ChatMessage\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"5\n\x13\x41\x64\x64MemoriesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\">\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"B\n\x0eSearchResponse\x12\x10\n\x08memories\x18\x01 \x03(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xf9\x01\n\x11\x43hatMemoryService\x12G\n\x10\x43hatWithMemories\x12\x18.chat_memory.ChatRequest\x1a\x19.chat_memory.ChatResponse\x12P\n\x0b\x41\x64\x64Memories\x12\x1f.chat_memory.AddMemoriesRequest\x1a .chat_memory.AddMemoriesResponse\x12I\n\x0eSearchMemories\x12\x1a.chat_memory.SearchRequest\x1a\x1b.chat_memory.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=34
  _globals['_CHATREQUEST']._serialized_end=118
  _globals['_CHATRESPONSE']._serialized_start=120
  _globals['_CHATRESPONSE']._serialized_end=211
  _globals['_ADDMEMORIESREQUEST']._serialized_start=213
  _globals['_ADDMEMORIESREQUEST']._serialized_end=294
  _globals['_ADDMEMORIESRESPONSE']._serialized_start=296
  _globals['_ADDMEMORIESRESPONSE']._serialized_end=349
  _globals['_SEARCHREQUEST']._serialized_start=351
  _globals['_SEARCHREQUEST']._serialized_end=413
  _globals['_SEARCHRESPONSE']._serialized_start=415
  _globals['_SEARCHRESPONSE']._serialized_end=481
  _globals['_CHATMESSAGE']._serialized_start=483
  _globals['_CHATMESSAGE']._serialized_end=527
  _globals['_CHATMEMORYSERVICE']._serialized_start=530
  _globals['_CHATMEMORYSERVICE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
