# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_memory_pb2 as chat__memory__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatMemoryServiceStub(object):
    """The memory service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatWithMemories = channel.unary_unary(
                '/chat_memory.ChatMemoryService/ChatWithMemories',
                request_serializer=chat__memory__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__memory__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.AddMemories = channel.unary_unary(
                '/chat_memory.ChatMemoryService/AddMemories',
                request_serializer=chat__memory__pb2.AddMemoriesRequest.SerializeToString,
                response_deserializer=chat__memory__pb2.AddMemoriesResponse.FromString,
                _registered_method=True)
        self.SearchMemories = channel.unary_unary(
                '/chat_memory.ChatMemoryService/SearchMemories',
                request_serializer=chat__memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=chat__memory__pb2.SearchResponse.FromString,
                _registered_method=True)


class ChatMemoryServiceServicer(object):
    """The memory service definition
    """

    def ChatWithMemories(self, request, context):
        """Searches for relevant memories and generates a chat response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMemories(self, request, context):
        """Adds new memories to the system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemories(self, request, context):
        """Searches for memories without generating a response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatMemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatWithMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatWithMemories,
                    request_deserializer=chat__memory__pb2.ChatRequest.FromString,
                    response_serializer=chat__memory__pb2.ChatResponse.SerializeToString,
            ),
            'AddMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMemories,
                    request_deserializer=chat__memory__pb2.AddMemoriesRequest.FromString,
                    response_serializer=chat__memory__pb2.AddMemoriesResponse.SerializeToString,
            ),
            'SearchMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemories,
                    request_deserializer=chat__memory__pb2.SearchRequest.FromString,
                    response_serializer=chat__memory__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_memory.ChatMemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_memory.ChatMemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatMemoryService(object):
    """The memory service definition
    """

    @staticmethod
    def ChatWithMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_memory.ChatMemoryService/ChatWithMemories',
            chat__memory__pb2.ChatRequest.SerializeToString,
            chat__memory__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_memory.ChatMemoryService/AddMemories',
            chat__memory__pb2.AddMemoriesRequest.SerializeToString,
            chat__memory__pb2.AddMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_memory.ChatMemoryService/SearchMemories',
            chat__memory__pb2.SearchRequest.SerializeToString,
            chat__memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
